[package]
name = "manager"
version = "0.1.0"
edition = "2018"

[dependencies]
shiplift = "0.7"
tokio = { version = "1", features = ["full", "time"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
futures-util = "0.3.12"
reqwest = { version = "0.11.0", features = ["json"] }